INSERT INTO USER (USERNAME, PASSWORD, ROLE) VALUES ('admin', '$2a$10$lW9Q6thFdccwPiRyOmQmreEtNhERoYGEsYKRL3uV97Q9u2ZGKxusW', 'ROLE_ADMIN');
INSERT INTO ELEMENT (ELEMENT_NAME, FIRST_PARENT, SECOND_PARENT) VALUES ('harom', null, null);
