INSERT INTO USER (USERNAME, PASSWORD, ROLE) VALUES ('admin', '$2a$10$lW9Q6thFdccwPiRyOmQmreEtNhERoYGEsYKRL3uV97Q9u2ZGKxusW', 'ROLE_ADMIN');
INSERT INTO ELEMENT (ELEMENT_NAME, FIRST_PARENT, SECOND_PARENT) VALUES ('viz', null, null);
INSERT INTO ELEMENT (ELEMENT_NAME, FIRST_PARENT, SECOND_PARENT) VALUES ('fold', null, null);
INSERT INTO ELEMENT (ELEMENT_NAME, FIRST_PARENT, SECOND_PARENT) VALUES ('sar', 'viz', 'fold');
INSERT INTO ELEMENT_USERS(ELEMENTS_ID,USERS_ID) VALUES(1,1);
INSERT INTO ELEMENT_USERS(ELEMENTS_ID,USERS_ID) VALUES(2,1);
